name: escritorioappf
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^2.0.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.5
  mysql1: ^0.20.0
  email_validator: ^2.1.17
  introduction_screen: ^3.0.1
  mask_text_input_formatter: ^2.4.0
  another_stepper: ^1.0.4
  intl: 0.17.0
  empty_widget: ^0.0.5  
  url_launcher: ^6.1.6
  http: ^0.13.5
  onesignal_flutter: ^3.4.2
  html_unescape: ^2.0.0
  whatsapp_unilink: ^2.0.2
  flutter_html: ^3.0.0-alpha.3
  auto_size_text: ^3.0.0
  smooth_page_indicator: ^1.0.0+2
  connectivity: ^3.0.6
  rounded_loading_button: ^2.0.8
  shared_preferences: ^2.0.15
  validatorless: ^1.2.3
  overlay_support: ^2.1.0
  connectivity_plus: ^3.0.3
  flutter_app_version_checker: ^0.3.2  
  provider: ^6.0.5
  local_auth: ^2.1.6
  shimmer: ^2.0.0
  badges: ^3.1.1
  flutter_launcher_icons: ^0.10.0
  
# icone ao abrir o app
  # flutter_native_splash: ^2.2.12
# flutter_native_splash:
#   color: "#42a5f5"  
#   image: assets/icons/logo.png


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  fluttertoast: ^8.1.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: 'assets/logo.png'
  

flutter:
  uses-material-design: true

  assets:
  #   - assets/images/
      - assets/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
